name: Deploy Trading Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write      
  contents: read       

jobs:
  deploy:
    name: Build & Deploy with SAM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::481665109942:role/GitHubActions
          role-session-name: github-deploy-session
          aws-region: us-east-1

      - name: Build Lambda Layer Dependencies
        run: |
          echo "Building Python Lambda Layer..." 
          mkdir -p layer/python

          pip install -r layer/layer-requirements.txt -t layer/python

          cd layer
          zip -r ../layer.zip python

        shell: bash

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM Application (Amazon Linux 2023)
        run: |
          sam build --use-container

      - name: Deploy SAM Application
        run: |
          sam deploy \
            --no-confirm-changeset \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --stack-name trading-bot \
            --region us-east-1
